services:
  db:
    image: postgres:17
    volumes:
      - ./db_setup:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "ongaku"
      POSTGRES_USER: "ongaku"
      POSTGRES_PASSWORD: ""
    healthcheck:
      test: pg_isready -U ongaku -d ongaku
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://ongaku:pass_example@db/ongaku?sslmode=disable", "up"]